hostname="kaizor"

# Networking
ifconfig_DEFAULT="DHCP"
sshd_enable="YES"

# Base Services
devd_enable="YES"
syslogd_enable="YES"
cron_enable="YES"

# Desktop runtime services
dbus_enable="YES"
hald_enable="YES"

# Optional: enable sound service later
# sndiod_enable="YES"
