autoboot_delay="2"
boot_verbose="YES"

# GPU Drivers (FreeBSD KMS)
kld_list="i915kms amdgpu radeonkms"

# Sound
snd_hda_load="YES"

# Networking drivers placeholder
if_wlan_load="YES"
if_re_load="YES"

kern.vty=vt
