name: Kaizor OS Build

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Tools
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake

      - name: Compile Kaizor
        run: |
          g++ main.cpp -o kaizor

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: kaizor-build
          path: kaizor
